- continuous_delivery_scripts/assert_news.py
- news/202108101821.bugfix
> fix github access

- azure-pipelines/build-release.yml
- continuous_delivery_scripts/assert_news.py
- continuous_delivery_scripts/utils/news_file.py
- news/202108110106.bugfix
Improve logging when asserting news files
> Improve logging when asserting news files

- continuous_delivery_scripts/assert_news.py
- continuous_delivery_scripts/utils/git_helpers.py
- news/202108110247.bugfix
- news/20210811024701.bugfix
Fix bug with dependency update branches
> Fix assert news bug

- continuous_delivery_scripts/plugins/GOLAND.MD
- continuous_delivery_scripts/plugins/NOOP.MD
- continuous_delivery_scripts/plugins/PYTHON.MD
- continuous_delivery_scripts/plugins/docker.py
- continuous_delivery_scripts/plugins/golang.py
- continuous_delivery_scripts/plugins/noop.py
- continuous_delivery_scripts/plugins/python.py
- continuous_delivery_scripts/tag_and_release.py
- continuous_delivery_scripts/utils/configuration.py
- continuous_delivery_scripts/utils/language_specifics_base.py
- news/202108111714.doc
- news/202108112203.feature
> ✨Added a golang plugin

- continuous_delivery_scripts/create_news_file.py
- continuous_delivery_scripts/tag_and_release.py
- news/202108240918.bugfix
> Fix bug in tag and release

- continuous_delivery_scripts/plugins/golang.py
- continuous_delivery_scripts/tag_and_release.py
- news/202108241747.bugfix
Fix golang packaging and releasing
> Fix golang packaging and releasing

- continuous_delivery_scripts/tag_and_release.py
- news/202108241912.bugfix
> Fix repository cleanup

- continuous_delivery_scripts/plugins/golang.py
- continuous_delivery_scripts/tag_and_release.py
- continuous_delivery_scripts/utils/language_specifics_base.py
- news/202108242145.feature
Added option to clean repository before packaging
> Added option to clean repository before packaging

- continuous_delivery_scripts/plugins/golang.py
- news/202108242248.bugfix
> [GO] Fixing issue with goreleaser

- continuous_delivery_scripts/plugins/GOLAND.MD
- continuous_delivery_scripts/plugins/golang.py
- news/202203220937.bugfix
> 💚️ Fix golang plugin for go>1.18

- continuous_delivery_scripts/plugins/golang.py
- news/202203221309.bugfix
changing the running directory
> Fix how golds is run

- .github/dependabot.yml
- .github/workflows/ci.yml
- .secrets.baseline
- Pipfile
- continuous_delivery_scripts/spdx_report/spdx_helpers.py
- continuous_delivery_scripts/utils/language_specifics_base.py
- news/202211301645.misc
- news/202211301646.bugfix
- pyproject.toml
- setup.py
> :gear: Change dependencies locking

- .github/workflows/release.yml
- news/202212011822.misc
> :gear: fix the release CI

- continuous_delivery_scripts/plugins/ci.py
- continuous_delivery_scripts/plugins/golang.py
- continuous_delivery_scripts/utils/language_specifics_base.py
- continuous_delivery_scripts/utils/versioning.py
- news/20221221110243.bugfix
- tests/versioning/test_versioning.py
Tags were rendered wrongly for plugins in which format is changed for versions such as Golang
> :bug: Fix tag rendering

- continuous_delivery_scripts/utils/versioning.py
- news/20221221151424.bugfix
- tests/versioning/test_versioning.py
> 🐛 Fix tag rendering

- continuous_delivery_scripts/utils/git_helpers.py
- news/20221221183120.bugfix
- tests/git_helper/test_git_helpers.py
Make sure staged changes are applied to clones
> :bug: Make sure staged changes are applied to clones

- .secrets.baseline
- continuous_delivery_scripts/plugins/GITHUB_ACTIONS.MD
- continuous_delivery_scripts/plugins/ci.py
- continuous_delivery_scripts/plugins/docker.py
- continuous_delivery_scripts/plugins/github_actions.py
- continuous_delivery_scripts/plugins/golang.py
- continuous_delivery_scripts/plugins/noop.py
- continuous_delivery_scripts/plugins/python.py
- continuous_delivery_scripts/tag_and_release.py
- continuous_delivery_scripts/utils/language_specifics_base.py
- continuous_delivery_scripts/utils/versioning.py
- news/20221221204057.feature
> :sparkles: Added `github_actions` plugin

- .secrets.baseline
- continuous_delivery_scripts/language_specifics.py
- continuous_delivery_scripts/plugins/BASIC.MD
- continuous_delivery_scripts/plugins/__init__.py
- continuous_delivery_scripts/plugins/basic.py
- continuous_delivery_scripts/plugins/ci.py
- continuous_delivery_scripts/plugins/docker.py
- continuous_delivery_scripts/plugins/golang.py
- continuous_delivery_scripts/plugins/noop.py
- continuous_delivery_scripts/plugins/python.py
- news/20221222001622.feature
- news/20221222001818.major
- news/20221222001917.bugfix
- tests/plugin/test_plugin.py
- Fixed plugin loader
- Added a basic plugin
- redefined the NoOp plugin
> :bug: Fixed plugin loader

- continuous_delivery_scripts/plugins/NOOP.MD
- continuous_delivery_scripts/utils/versioning.py
- news/20221222112207.bugfix
- tests/versioning/test_versioning.py
> :bug: fix prerelease shortcut tags

- .github/workflows/ci.yml
- news/202301251550.bugfix
- pyproject.toml
- setup.py
Breaking changes were introduced in a minor release https://github.com/spdx/tools-python/releases/tag/v0.7.0. Therefore fixing the version
> :bug: fix dependency version

- news/202303011436.misc
- pyproject.toml
> :gear: revert the changelog title change
